2022-04-25 15:40:01,387 INFO    MainThread:23949 [wandb_setup.py:_flush():75] Loading settings from /home/lechapelier/.config/wandb/settings
2022-04-25 15:40:01,387 INFO    MainThread:23949 [wandb_setup.py:_flush():75] Loading settings from /home/lechapelier/Documents/Stage M2/moral_rl/wandb/settings
2022-04-25 15:40:01,387 INFO    MainThread:23949 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-25 15:40:01,387 WARNING MainThread:23949 [wandb_setup.py:_flush():75] Could not find program at -m moral.ppo_train
2022-04-25 15:40:01,388 INFO    MainThread:23949 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m moral.ppo_train'}
2022-04-25 15:40:01,388 INFO    MainThread:23949 [wandb_init.py:_log_setup():438] Logging user logs to /home/lechapelier/Documents/Stage M2/moral_rl/wandb/run-20220425_154001-vlzxekex/logs/debug.log
2022-04-25 15:40:01,388 INFO    MainThread:23949 [wandb_init.py:_log_setup():439] Logging internal logs to /home/lechapelier/Documents/Stage M2/moral_rl/wandb/run-20220425_154001-vlzxekex/logs/debug-internal.log
2022-04-25 15:40:01,388 INFO    MainThread:23949 [wandb_init.py:init():472] calling init triggers
2022-04-25 15:40:01,388 INFO    MainThread:23949 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'env_id': 'randomized_v3', 'env_steps': 9000000.0, 'batchsize_ppo': 12, 'n_workers': 12, 'lr_ppo': 0.0003, 'entropy_reg': 0.05, 'lambd': [0, 0, 1, 1], 'gamma': 0.999, 'epsilon': 0.1, 'ppo_epochs': 5}
2022-04-25 15:40:01,388 INFO    MainThread:23949 [wandb_init.py:init():525] starting backend
2022-04-25 15:40:01,388 INFO    MainThread:23949 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-25 15:40:01,399 INFO    MainThread:23949 [backend.py:ensure_launched():219] starting backend process...
2022-04-25 15:40:01,406 INFO    MainThread:23949 [backend.py:ensure_launched():224] started backend process with pid: 23972
2022-04-25 15:40:01,408 INFO    MainThread:23949 [wandb_init.py:init():534] backend started and connected
2022-04-25 15:40:01,412 INFO    MainThread:23949 [wandb_init.py:init():598] updated telemetry
2022-04-25 15:40:01,437 INFO    MainThread:23949 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-25 15:40:02,960 WARNING MainThread:23949 [wandb_init.py:init():1017] interrupted
Traceback (most recent call last):
  File "/home/lechapelier/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    run = wi.init()
  File "/home/lechapelier/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 630, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/home/lechapelier/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/lechapelier/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 323, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/lechapelier/.local/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 225, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/lechapelier/.local/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
